'''
==============================================================================
  Unit 3: Strings & Lists  ·  Session 1  ·  Version 3
  Problem 4: Find the Imposter

  Write a function `find_difference()` that takes two strings as parameters.
  The second string is generated by shuffling the first string and adding
  one more letter at a random position. Search for and return the added
  letter.

  Write your solution for `find_difference` in the space below,
  then click  ▶ Run  to grade it.
  (The full problem, with examples, is in the problem set.)

  ⚠️  Keep the function name `find_difference` and its parameters exactly as given —
      the problem set solution validator looks for that exact name.
==============================================================================
Understand (input, output, core logic): 

Match:

Plan:

'''


def find_difference(s1, s2):
    pass

s1 = "abcd"
s2 = "baedc"
print(find_difference(s1, s2))

# ==== AI-generated test cases (added by Claude via Claude Code) ====
# These are AI-generated edge-case tests, not part of the original CodePath problem set.
# They check correctness beyond the single example call above.

print("Test 1 - minimal case, single character strings")
print("  expected:", "b", "| got:", find_difference("a", "ba"))

print("Test 2 - added letter is a duplicate of an existing letter")
print("  expected:", "a", "| got:", find_difference("aa", "aaa"))

print("Test 3 - longer strings")
print("  expected:", "z", "| got:", find_difference("abcdef", "fecdzba"))


'''
==============================================================================
  PROBLEM SET SOLUTION VALIDATOR   ·   DO NOT EDIT OR MOVE THIS SECTION
==============================================================================
'''
import sys, pathlib
for _p in pathlib.Path(__file__).resolve().parents:
    if (_p / "ProblemSetSolutionValidator[DO_NOT_EDIT]").is_dir():
        sys.path.insert(0, str(_p / "ProblemSetSolutionValidator[DO_NOT_EDIT]")); break
from problem_set_solution_validator import grade, test

grade(find_difference)   # ▶ Run this file to validate your solution

'''
==============================================================================
  YOUR OWN TEST CASES   ·   optional — uncomment & edit to try your own inputs
==============================================================================
'''
# test('abcd', 'baedc', expected='e')   # checks the value your code returns against this example
